apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-micro-service
spec:
  selector:
    matchLabels:
      app: java-micro-service
  replicas: 1
  template:
    metadata:
      labels:
        app: java-micro-service
    spec:
      containers:
        - name: java-micro-service
          image: dock123sapna/java-micro-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongodb:27017/serverdb